[package]
name = "eco_legacy"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.13.1"
ic-cdk-macros = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4"